// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes a non-blocking Send to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Send queues a notification; never blocks or breaks the timer flow. Drops if busy.
 */
export function Send(title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(3627263562, title, body);
}
