// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes a single non-blocking Send(title, body) to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Send queues a native notification and returns immediately. Errors from the
 * toast path are logged, never surfaced — a notification must never break the
 * timer flow. If the worker is already backed up the toast is dropped.
 */
export function Send(title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(3627263562, title, body);
}
