// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes the SQLite-backed checklist to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * AddTodo inserts a new task. The frontend passes active=true when this is the
 * only task, so it becomes the current task immediately.
 */
export function AddTodo(text: string, active: boolean): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(154452291, text, active).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetTodos(): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(3062610549).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveTodo deletes a task. The frontend passes the id to make active next
 * ("" = leave the current pin unchanged).
 */
export function RemoveTodo(id: string, nextActive: string): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(2143946512, id, nextActive).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetActiveTodo pins id as the current task (empty id clears the pin).
 */
export function SetActiveTodo(id: string): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(1186945738, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ToggleTodo flips done. The frontend passes the id to make active next ("" =
 * leave the current pin unchanged).
 */
export function ToggleTodo(id: string, nextActive: string): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(1376018004, id, nextActive).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateTodo edits a task's text and notes.
 */
export function UpdateTodo(id: string, text: string, notes: string): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(3348647097, id, text, notes).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.Todo.createFrom;
const $$createType1 = $Create.Array($$createType0);
