// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service persists the todo list slice of the config.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function AddTodo(text: string): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(154452291, text).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetTodos(): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(3062610549).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RemoveTodo(id: string): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(2143946512, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ToggleTodo(id: string): $CancellablePromise<config$0.Todo[]> {
    return $Call.ByID(1376018004, id).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.Todo.createFrom;
const $$createType1 = $Create.Array($$createType0);
