// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Settings are the timer durations and automation toggles.
 */
export class Settings {
    "focusMinutes": number;
    "shortBreakMinutes": number;
    "longBreakMinutes": number;
    "longBreakInterval": number;
    "autoStartBreaks": boolean;
    "autoStartFocus": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("focusMinutes" in $$source)) {
            this["focusMinutes"] = 0;
        }
        if (!("shortBreakMinutes" in $$source)) {
            this["shortBreakMinutes"] = 0;
        }
        if (!("longBreakMinutes" in $$source)) {
            this["longBreakMinutes"] = 0;
        }
        if (!("longBreakInterval" in $$source)) {
            this["longBreakInterval"] = 0;
        }
        if (!("autoStartBreaks" in $$source)) {
            this["autoStartBreaks"] = false;
        }
        if (!("autoStartFocus" in $$source)) {
            this["autoStartFocus"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * Stats feed the daily report (pomodoros completed, round number).
 */
export class Stats {
    "sessionsCompleted": number;
    "round": number;
    "lastCompletedAt": number;

    /** Creates a new Stats instance. */
    constructor($$source: Partial<Stats> = {}) {
        if (!("sessionsCompleted" in $$source)) {
            this["sessionsCompleted"] = 0;
        }
        if (!("round" in $$source)) {
            this["round"] = 0;
        }
        if (!("lastCompletedAt" in $$source)) {
            this["lastCompletedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     */
    static createFrom($$source: any = {}): Stats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats($$parsedSource as Partial<Stats>);
    }
}

/**
 * TimerState is the live timer position.
 */
export class TimerState {
    /**
     * focus | shortBreak | longBreak
     */
    "phase": string;

    /**
     * idle | running | paused | finished
     */
    "status": string;
    "remainingMs": number;
    "totalMs": number;

    /** Creates a new TimerState instance. */
    constructor($$source: Partial<TimerState> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("remainingMs" in $$source)) {
            this["remainingMs"] = 0;
        }
        if (!("totalMs" in $$source)) {
            this["totalMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimerState instance from a string or object.
     */
    static createFrom($$source: any = {}): TimerState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimerState($$parsedSource as Partial<TimerState>);
    }
}

/**
 * Todo is a single daily checklist item, persisted in SQLite.
 */
export class Todo {
    "id": string;
    "text": string;
    "done": boolean;
    "notes"?: string;
    "active"?: boolean;
    "createdAt": number;

    /** Creates a new Todo instance. */
    constructor($$source: Partial<Todo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Todo instance from a string or object.
     */
    static createFrom($$source: any = {}): Todo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Todo($$parsedSource as Partial<Todo>);
    }
}
