// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes the persisted settings, timer state, and stats to the
 * frontend. One service for the whole JSON config file (previously three
 * separate settings/stats/timer services that each wrapped the same store).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(503514218).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetStats(): $CancellablePromise<$models.Stats> {
    return $Call.ByID(1439423802).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetTimerState(): $CancellablePromise<$models.TimerState> {
    return $Call.ByID(743539873).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateSettings(settings: $models.Settings): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2199452473, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateStats(stats: $models.Stats): $CancellablePromise<$models.Stats> {
    return $Call.ByID(3263236991, stats).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateTimerState(state: $models.TimerState): $CancellablePromise<$models.TimerState> {
    return $Call.ByID(1908627254, state).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
const $$createType1 = $models.Stats.createFrom;
const $$createType2 = $models.TimerState.createFrom;
