// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service persists the timer settings slice of the config.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(1980469277).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateSettings(settings: config$0.Settings): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(223465560, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.Settings.createFrom;
