// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service persists the stats slice of the config. The frontend computes the
 * counters (it owns the phase logic) and hands them over to persist.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function GetStats(): $CancellablePromise<config$0.Stats> {
    return $Call.ByID(561553037).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateStats(stats: config$0.Stats): $CancellablePromise<config$0.Stats> {
    return $Call.ByID(708373166, stats).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.Stats.createFrom;
