// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service persists the timer slice of the config.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function GetTimerState(): $CancellablePromise<config$0.TimerState> {
    return $Call.ByID(4104771542).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateTimerState(state: config$0.TimerState): $CancellablePromise<config$0.TimerState> {
    return $Call.ByID(896182891, state).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.TimerState.createFrom;
